<div class="jumbotron">
	<h1>Welcome!<?php echo Html::img('assets/img/brand.png') ?></h1>
	<p>This admin panel has been generated by the FuelPHP Framework.</p>
</div>
<div class="row">
	<div class="col-md-4">
		<h2><?php echo Html::img('assets/img/about.png')?><span style="margin-left: 10px;">About</span></h2>
		<p>about this application (lei, pat: himu.i.., please.., xDD thnx.., )</p>
	</div>
	<div class="col-md-4">
		<h2><?php echo Html::img('assets/img/statistics.png')?><span style="margin-left: 10px;">Statistics</span></h2>
		<p>Plant Entries: ###</p>
		<p>Image Entries: ###</p>
		<p>Last Update: MM/DD/YY</p>
	</div>
	<div class="col-md-4">
		<h2><?php echo Html::img('assets/img/developer.png')?><span style="margin-left: 10px;">Other platform</span></h2>
		<p>Available in <b>Android</b>... <i>for now... ^^,</i></p>
		<ul>
			<li><?php echo Html::img('assets/img/android_icon.png') ?><a href="http://play.google.com">Android</a></li>
		</ul>
	</div>
</div>