<div class="jumbotron">
	<h1>Welcome!<?php echo Html::img('assets/img/brand.png') ?></h1>
	<p>This admin panel has been generated by the FuelPHP Framework.</p>
</div>
<div class="row">
	<div class="col-md-4">
		<h2><?php echo Html::img('assets/img/about.png')?><span style="margin-left: 10px;">About</span></h2>
		<p>about this application (lei, pat: himu.i.., please.., xDD thnx.., )</p>
	</div>
	<div class="col-md-4">
		<h2><?php echo Html::img('assets/img/statistics.png')?><span style="margin-left: 10px;">Statistics</span></h2>
		
		<?php

			$count_plant = DB::query("SELECT COUNT(*) FROM `plants`")->execute()->as_array();
			$count_image = DB::query("SELECT COUNT(*) FROM `images`")->execute()->as_array();
			$last_update = DB::query("SELECT FROM `publishes` ORDER BY `id` LIMIT 1");

			echo "<strong><p>Plant Entries: </strong>".$count_plant[0]['COUNT(*)'];
			echo "<strong><p>Image Entries: </strong>".$count_image[0]['COUNT(*)'];
			echo "<p>Last Update: MM/DD/YY</p>";
		?>

	</div>
	<div class="col-md-4">
		<h2><?php echo Html::img('assets/img/developer.png')?><span style="margin-left: 10px;">Other platform</span></h2>
		<p>Available in <b>Android</b>... <i>for now... ^^,</i></p>
		<ul>
			<li><?php echo Html::img('assets/img/android_icon.png') ?><a href="http://play.google.com">Android</a></li>
		</ul>
	</div>
</div>